import { Problem } from "@/app/types/problem";

export const problems: Problem[] = [
  {
    id: 1,
    title: "Two Sum",
    difficulty: "Easy",
    status: "Solved",
    acceptance: 56.7,
    topics: ["Array"],
    languages: ["Python", "JavaScript"],
  },
  {
    id: 10,
    title: "Regex Matching",
    difficulty: "Hard",
    status: "Attempted",
    acceptance: 30.1,
    topics: ["DP", "String"],
    languages: ["C++"],
  },

  {
    id: 3,
    title: "Longest Substring Without Repeating Characters",
    difficulty: "Medium",
    status: "Solved",
    acceptance: 38.1,
    topics: ["String", "Sliding Window"],
    languages: ["Python", "Java"],
  },
  {
    id: 4,
    title: "Median of Two Sorted Arrays",
    difficulty: "Hard",
    status: "Unsolved",
    acceptance: 45.4,
    topics: ["Binary Search"],
    languages: ["C++", "Java"],
  },
  {
    id: 5,
    title: "Longest Palindromic Substring",
    difficulty: "Medium",
    status: "Solved",
    acceptance: 36.9,
    topics: ["String", "DP"],
    languages: ["Python"],
  },
  {
    id: 6,
    title: "Zigzag Conversion",
    difficulty: "Medium",
    status: "Solved",
    acceptance: 53.1,
    topics: ["String"],
    languages: ["JavaScript"],
  },
  {
    id: 7,
    title: "Reverse Integer",
    difficulty: "Medium",
    status: "Attempted",
    acceptance: 31.2,
    topics: ["Math"],
    languages: ["Python", "C++"],
  },
  {
    id: 8,
    title: "String to Integer (atoi)",
    difficulty: "Medium",
    status: "Unsolved",
    acceptance: 20.3,
    topics: ["String"],
    languages: ["Java"],
  },
  {
    id: 9,
    title: "Palindrome Number",
    difficulty: "Easy",
    status: "Solved",
    acceptance: 60.0,
    topics: ["Math"],
    languages: ["Python", "JavaScript"],
  },
  {
    id: 11,
    title: "Container With Most Water",
    difficulty: "Medium",
    status: "Solved",
    acceptance: 59.2,
    topics: ["Two Pointers"],
    languages: ["Python"],
  },
  {
    id: 12,
    title: "Integer to Roman",
    difficulty: "Medium",
    status: "Attempted",
    acceptance: 70.0,
    topics: ["Math", "String"],
    languages: ["JavaScript"],
  },
  {
    id: 13,
    title: "Roman to Integer",
    difficulty: "Easy",
    status: "Solved",
    acceptance: 65.9,
    topics: ["Hash Map"],
    languages: ["Python"],
  },
  {
    id: 14,
    title: "Longest Common Prefix",
    difficulty: "Easy",
    status: "Solved",
    acceptance: 46.7,
    topics: ["String"],
    languages: ["Java"],
  },
  {
    id: 15,
    title: "3Sum",
    difficulty: "Medium",
    status: "Unsolved",
    acceptance: 32.8,
    topics: ["Two Pointers", "Sorting"],
    languages: ["C++"],
  },
  {
    id: 16,
    title: "3Sum Closest",
    difficulty: "Medium",
    status: "Attempted",
    acceptance: 48.9,
    topics: ["Two Pointers"],
    languages: ["Python"],
  },
  {
    id: 17,
    title: "Letter Combinations of a Phone Number",
    difficulty: "Medium",
    status: "Solved",
    acceptance: 58.3,
    topics: ["Backtracking"],
    languages: ["JavaScript"],
  },
  {
    id: 18,
    title: "4Sum",
    difficulty: "Medium",
    status: "Unsolved",
    acceptance: 35.6,
    topics: ["Two Pointers", "Sorting"],
    languages: ["C++", "Java"],
  },
  {
    id: 19,
    title: "Remove Nth Node From End of List",
    difficulty: "Medium",
    status: "Solved",
    acceptance: 42.1,
    topics: ["Linked List", "Two Pointers"],
    languages: ["Python"],
  },
  {
    id: 20,
    title: "Valid Parentheses",
    difficulty: "Easy",
    status: "Solved",
    acceptance: 41.7,
    topics: ["Stack"],
    languages: ["JavaScript"],
  },
  {
    id: 21,
    title: "Merge Two Sorted Lists",
    difficulty: "Easy",
    status: "Solved",
    acceptance: 63.4,
    topics: ["Linked List"],
    languages: ["Python", "Java"],
  },
  {
    id: 22,
    title: "Generate Parentheses",
    difficulty: "Medium",
    status: "Attempted",
    acceptance: 73.9,
    topics: ["Backtracking"],
    languages: ["C++"],
  },
];


